# Generated by Django 6.0.6 on 2026-07-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_person_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('character', models.CharField(blank=True, max_length=200)),
                ('photo_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='movieapp.movie')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
